### ISSUE TITLE
[BUG] btop crashes on Raspberry Pi 2 with basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by Aluminite** [aristocratos/btop#11]
**Describe the bug**

When attempting to run on a Raspberry Pi 2, btop crashes immediately.

**To Reproduce**

1. Download btop for armhf, extract and install
2. Run it

**Expected behavior**

The program starts properly with no errors.

**Screenshots**

Terminal output:
```bash
pi@raspberrypi:~/btop $ sudo make install

 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Installer

Installing binary to: /usr/local/bin/btop
Installing doc to: /usr/local/share/btop
Installing themes to: /usr/local/share/btop/themes
pi@raspberrypi:~/btop $ sudo make setuid
File: /usr/local/bin/btop
Setting owner root:root
Setting SUID bit
pi@raspberrypi:~/btop $ btop
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

**Info (please complete the following information):**
 - btop++ version: btop version: 1.0.2
 - Architecture: armv7l
 - Platform: Linux (Raspberry Pi OS 2021-05-07)
 - Linux Kernel: 5.10.60-v7+
 - Terminal used: PuTTY over SSH
 - Font used: Source Code Pro Semibold

**Additional context**

Logs are very unhelpful:
```
2021/09/21 (01:24:34) | ===> btop++ v.1.0.2
2021/09/21 (01:24:34) | DEBUG: Starting in DEBUG mode!
2021/09/21 (01:24:34) | INFO: Logger set to DEBUG
```
[end of log file]

**Comment by aristocratos** [comment]
@Aluminite 
Try [release v1.0.3](https://github.com/aristocratos/btop/releases/tag/v1.0.3)

**Comment by Aluminite** [comment]
I tried v1.0.3 and v1.0.4 but the same issue persists.

**Comment by Aluminite** [comment]
I've got some more info on the issue. The issue doesn't seem to have anything to do with my RasPi, it's PuTTY.
I tried running it on two other systems (one a x86_64 desktop PC and another a VM running in QEMU under that same PC) through PuTTY and they both exhibited the same issue. Running it through the standard TTY gives no issues.
I also tried running it through SSH in Windows Terminal, same issue.

Here's a quick TL;DR for what I've tested and the results:

PuTTY SSH: crash
OpenSSH in Windows Terminal: crash
OpenSSH in standard cmd.exe: crash
JuiceSSH (Android): crash
macOS terminal over SSH: no crash
TTY: no crash

**Comment by aristocratos** [comment]
@Aluminite 
I haven't been able to reproduce it using either `putty` or `ssh` over `cmd.exe`.
So currently have no way to troubleshoot this. What SSH server are you running on your Pi?
I do remember there being issues with ssh'ing in to a `dropbear` server in `bpytop` or maybe `bashtop`.

**Comment by Aluminite** [comment]
@aristocratos 
I figured it out. All of the devices I was SSHing into were running `openssh-server`, and they had the setting `UsePAM` set to `no`. Manually re-enabling that setting makes btop run fine. Not quite sure _why_ that happens though.

**Comment by Aluminite** [comment]
Yep, it's the locale.
Here's the output of `locale` with `UsePAM` set to `no`:
```bash
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
And here it is with `UsePAM` set to `yes`:
```bash
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by aristocratos** [comment]
@Aluminite 
I found the problem, a call to `std::locale` was causing it when the `LANG` variable was set to a non existant locale.
Is fixed in [v1.0.5](https://github.com/aristocratos/btop/releases/tag/v1.0.5), should work regardless of if `UsePAM` is set now.

**Comment by Aluminite** [comment]
@aristocratos I'm still getting the exact same error on v1.0.5.

**Comment by aristocratos** [comment]
@Aluminite 
Huh, do you get the same error if you start with `LANG=C btop` or replace C with any UTF-8 locale on the system?

**Comment by Aluminite** [comment]
@aristocratos
If I run `export LANG=C` or even `export LANG=""`, it doesn't crash and gives the expected message that it can't detect UTF-8.
I think the problem is that by default, the `LANG` environment variable is actually **unset** and not blank. That's why setting it to an empty string doesn't crash, but running `unset LANG` after does crash.

**Comment by aristocratos** [comment]
@Aluminite 
Ah, got it. Try with latest commit, forgot to check for `NULL` using when using `getenv("LANG")`.
