### ISSUE TITLE
[UTF-8] No UTF-8 locale detected!

### ISSUE THREAD

**Issue by mustevenplay** [aristocratos/btop#166]
**Describe the bug**

Tried to install btop many times, and I still can't manage to run it.

**To Reproduce**

Very easy:
- make
- make install
- btop

**Expected behavior**

Btop working right away.

**Screenshots**

<img width="1440" alt="Screenshot 2021-11-22 at 00 25 10" src="https://user-images.githubusercontent.com/14057832/142783392-12ed494e-0ec4-4075-ab40-60f7cdbcb71d.png">

**Info (please complete the following information):**
 - btop++ version: 1.0.24
 - Binary: self compiled
 - (If compiled) Compiler and version: g++-11 [11.1.0]
 - Architecture: arm64
 - Platform: OSX
 - (Linux) Kernel: (OSX) 21.1.0
 - (OSX/FreeBSD) Os release version: 12.0.1
 - Terminal used: OSX built-in terminal (Terminal)
 - Font used: Roboto Mono Medium Nerd Font

**Additional context**

2021/11/22 (00:24:37) | ===> btop++ v.1.0.24
2021/11/22 (00:24:37) | ERROR: No UTF-8 locale detected!
Use --utf-force argument to force start if you're sure your terminal can handle it.

**Comment by aristocratos** [comment]
@mustevenplay 
If you read the error message it tells you that you can still run it using `btop --utf-force`.

But the UTF detection seems to be fishy on macos, so next release will be more forgiving in the detection on that platform.

**Comment by aristocratos** [comment]
@mustevenplay 
Fixed in v1.1.2

**Comment by mustevenplay** [comment]
Hugee! 🚀

**Comment by SwapnilSoni1999** [comment]
I'm still having the issue I've checked my /etc/locale.gen as well its en_US.UTF-8

**Comment by imwints** [comment]
Please upgrade to the latest version

**Comment by indranildeveloper** [comment]
I am still having this issue on CachyOS, I am on version 1.4.4 of btop. How I can fix that?

**Comment by AbhishekT-2002** [comment]
Quick fix for fish shell users encountering `No UTF-8 locale detected` error when running btop:

Add this line to `~/.config/fish/config.fish`:

set -x LANG en_US.UTF-8


> I am still having this issue on CachyOS, I am on version 1.4.4 of btop. How I can fix that?
